copy:
  - zip url | local directory path | local zip path | local file path
  - zip url | local directory path | local zip path | local file path
models:
  - zip url | local directory path | local zip path | local file path
  - zip url | local directory path | local zip path | local file path
nodes:
  git:
    - git clone url
    - git clone url
    - git clone url
  pip:
    - pip_package_1
    - pip_package_2 pip_package_3 pip_package_4
  node_requirements: true
